### ISSUE TITLE
CRAN additional checks errors

### ISSUE THREAD

**Issue by richfitz** [richfitz/dde#21]
Errors in UBSAN, valgrind and rchk.  These could possibly all point at the same thing.

**Comment by richfitz** [comment]
ubsan (clang):

```
docker pull wch1/r-debug
docker run -v $PWD:/src:ro --name=dde-debug -it --rm --security-opt seccomp=unconfined wch1/r-debug
RDcsan -e 'install.packages(c("deSolve", "knitr", "ring", "microbenchmark", "rmarkdown", "testthat", "devtools", "roxygen2"))'
rm -rf /dde ; cp -r /src /dde
RDcsan CMD INSTALL --preclean --install-tests /dde
RDcsan -e 'tools::testInstalledPackage("dde")'
cat dde-tests/testthat.Rout
```

Somewhat more minimal:

```
RDcsan
loadNamespace("deSolve")
devtools::load_all("dde")
run_seir_dde(seq(0, 30, length.out = 301), n_history = 2L)
```

gives the error:

```
    #0 0x7f5d6334b95a in dopri_find_time /dde/src/dopri.c:745:21
    #1 0x7f5d6334c097 in ylag_1 /dde/src/dopri.c:769:24
    #2 0x7f5d618ae83a in ylag_1 /dde/inst/include/dde/dde.c:15:10
    #3 0x7f5d618ae0f4 in seir /tmp/RtmpHnSOo7/filee35223bff66/seir.c:13:18
    #4 0x7f5d63346764 in dopri_eval /dde/src/dopri.c:822:3
    #5 0x7f5d63350400 in dopri5_step /dde/src/dopri_5.c:75:3
    #6 0x7f5d6333e58f in dopri_step /dde/src/dopri.c:253:5
    #7 0x7f5d63341457 in dopri_integrate /dde/src/dopri.c:377:5
    #8 0x7f5d6336a4e0 in r_dopri /dde/src/r_dopri.c:176:3
    #9 0x7f5d7ade46a6 in R_doDotCall /tmp/r-source/src/main/dotcode.c:744:17
...
```

offending code is:

```
  size_t idx0 = 0;
  if (n > 0) {
    const double
      t0 = ((double*) ring_buffer_tail(obj->history))[idx_t],
      t1 = ((double*) ring_buffer_tail_offset(obj->history, n - 1))[idx_t];
    idx0 = min_size((t - t0) / (t1 - t0) / (n - 1), n - 1);
  }
```

so this one should be straightforward to fix

**Comment by richfitz** [comment]
Moved to mrc-1281 and discussion moved to a blog post (reside-89)
